### ISSUE TITLE
Bug: The Magazine Subscribe block does not appear on non-live pages

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#12]
### Issue Type

Bug

### Priority

None

### Description

The Magazine Subscribe block does not appear on non-live pages.

### Affected Device Classes

All

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/magazine-subscribe
2. Observe the page.

### Expected Results

The Magazine Subscribe block should be visible on the page.

### Actual Results

- The Magazine Subscribe block is not showing on the page.

- The `data-section-status` attribute remains in the loading state, which applies `display: none` to the `magazine-subscribe-container`.

- An error that might be related is shown in the console:
```
Uncaught SecurityError: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at piGetCookie (pd.js:5:3570)
    at piTracker (pd.js:5:349)
    at pd.js:5:4028
```

**Comment by amglebihan** [comment]
We had a call about this with Kannan and noticed that the block is displayed correctly on all live pages, such as [this one](https://www.macktrucks.com/magazine/articles/2023/january/granite-grille-and-led-headlights). However, it doesn’t appear on pages like [this one](https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/magazine-subscribe). I’ve updated the actual results section with some details.
